# -*- coding: utf-8 -*-
"""Copy of Tuesday_work.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwTNmzg5Bt2drwcja07ye35q3KPJKB3x

## Question 1

- `Take two integer numbers and return their product. If the product is greater than 1000, then return their sum if product is less than 1000 return product value only.`
"""

# Please write The solution Here for above question 1:
a=int(input("Enter a num1: "))
b=int(input("Enter a num2: "))
sum=0
product=a*b
if product > 1000:
  print("sum: ",a+b)
else:
  print("product: ",product)

"""## question 2

- `Given a range of the first 10 numbers, Iterate from the start number to the end number, and In each iteration print the sum of the current number and previous number`

Expected output:
-----------------
    Printing current and previous number sum in a range(10)
    Current Number 0 Previous Number  0  Sum:  0
    Current Number 1 Previous Number  0  Sum:  1
    Current Number 2 Previous Number  1  Sum:  3
    Current Number 3 Previous Number  2  Sum:  5
    Current Number 4 Previous Number  3  Sum:  7
    Current Number 5 Previous Number  4  Sum:  9
    Current Number 6 Previous Number  5  Sum:  11
    Current Number 7 Previous Number  6  Sum:  13
    Current Number 8 Previous Number  7  Sum:  15
    Current Number 9 Previous Number  8  Sum:  17
"""

# Please write The solution Here for above question 2:
print("Printing current and previous number sum in a range(10)")
previous_value=0

for current_value in range(10):
  sum=current_value + previous_value
  print("Current Number", current_value,
          "Previous Number", previous_value,
          "Sum:", sum)
  previous_value=current_value

"""## question 3

Given a string and an integer number n, remove characters from a string starting from zero up to n and return a new string

- Example :
     `("pynative", 4) so output must be tive.`
     
     `Note: n must be less than the length of the string.`
"""

# Please write The solution Here for above question 3:
s=input("Enter a string: ")
n=int(input("Enter a number: "))

if n < len(s):
  new_string=s[n:]
  print("new string: ",new_string)
else:
    print("n must be less than the length of the string")

"""## question 4

### `Given a list of numbers, return True if first and last number of a list is same`

    Expected Output:
    -------------------------------------

    Given list is
    a =  [10, 20, 30, 40, 10]
    b = [10 , 20 , 30 , 40, 10 ]
    result is True

    Given list is  
    a = [10, 20, 30, 40, 50]
    b = [11 , 21 , 31 , 41 , 51 ]
    result is False
"""

# Please write The solution Here for above question 4:
a = [10, 20, 30, 40, 10]
b = [10 , 21 , 31 , 41 , 10]
if a[0]==b[-1]:
  print("result is true")
else:
  print("result is False")


nn

"""## question 5

### Given a two Python list. Iterate both lists simultaneously such that list1 should display item in original order and list2 in reverse order

    list1 = [10, 20, 30, 40]
    list2 = [100, 200, 300, 400]


    Expected output:
    -----------------------------
    10 400
    20 300
    30 200
    40 100
"""

# Please write The solution Here for above question 5:

list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]

for x, y in zip(list1, list2[::-1]):
    print(x, y)

"""## question 6

### Remove empty strings from the list of strings


    list1 = ["Mike", "", "Emma", "Kelly", "", "Brad"]

    Expected output:
    ----------------------

    ["Mike", "Emma", "Kelly", "Brad"]
"""

# Please write The solution Here for above question 6:

list1 = ["Mike", "", "Emma", "Kelly", "", "Brad"]

result = []

for item in list1:
    if item != "":
        result.append(item)

print(result)