# -*- coding: utf-8 -*-
"""Copy of Python_Dictionary .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRE98pQAOPBZT0dsSR76-WjSdCPC-nfp

<a href="https://www.viharatech.com"><img src="https://miro.medium.com/v2/resize:fit:828/format:webp/1*on2Bpj6A5gfd-CzaFOAZRA.jpeg"></a>


- `Welcome to our interactive learning session! In this Jupyter notebook, you'll find a series of questions related to Python Dictionary Concept. To maximize your learning, please write Python code in the cell below each question and execute it. This hands-on practice will help reinforce your understanding of the concepts. Feel free to reach out if you have any questions or need assistance. Happy coding! 💻🐍 `

### Question 1: Write a function that takes a dictionary and a key as input and returns the corresponding value.

- `Sample Input: my_dict = {'a': 1, 'b': 2, 'c': 3}, key = 'b'`
- `Sample Output: 2`
"""

# Please write The solution Here for above question 1:
my_dict={'a': 1, 'b': 2, 'c': 3}
print(my_dict['b'])

"""###  Question 2 : Write a function that updates a dictionary with a new key-value pair.

- `Sample Input: my_dict = {'a': 1, 'b': 2}, key = 'c', value = 3`
- `Sample Output:{'a': 1, 'b': 2, 'c': 3}`
"""

# Please write The solution Here for above question 2:
my_dict = {'a': 1, 'b': 2}
my_dict.update({"c":3})
print(my_dict)

"""### Question 3 : Write a function that checks if a key exists in a dictionary.
   - `Sample Input: my_dict = {'a': 1, 'b': 2, 'c': 3}, key = 'd'`
   - `Sample Output: False`
"""

# Please write The solution Here for above question 3:
my_dict = {'a': 1, 'b': 2, 'c': 3}
key="b"
if key not in my_dict:
  print("False")
else:
  print("True")

"""### Question 4 :  Write a function that calculates the sum of all values in a dictionary.

   - `Sample Input: my_dict = {'a': 1, 'b': 2, 'c': 3}`
   - `Sample Output: 6`
"""

from typing import ValuesView
# Please write The solution Here for above question 4:
my_dict = {'a': 1, 'b': 2, 'c': 3}
sum=0
for i in my_dict.values():
  sum+=i
print(sum)

"""### Question 5 : Write a function that returns a list of all keys in a dictionary.
   - `Sample Input: my_dict = {'a': 1, 'b': 2, 'c': 3}`
   - `Sample Output: ['a', 'b', 'c']`
"""

# Please write The solution Here for above question 5:
my_dict = {'a': 1, 'b': 2, 'c': 3}
print(my_dict.keys())

"""### Question 6 : Write a function that returns a list of all values in a dictionary.
   - `Sample Input: my_dict = {'a': 1, 'b': 2, 'c': 3}`
   - `Sample Output: [1, 2, 3]`
"""

# Please write The solution Here for above question 6:
my_dict = {'a': 1, 'b': 2, 'c': 3}
print(my_dict.values())

"""### Question 7 : Write a function that returns the number of key-value pairs in a dictionary.
   - `Sample Input: my_dict = {'a': 1, 'b': 2, 'c': 3}`
   - `Sample Output: 3`
"""

# Please write The solution Here for above question 7:
my_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
sum=0
for i in my_dict.values():
  sum+=1
print(sum)

"""### Question 8 : Write a function that merges two dictionaries into one.

- `Sample Input: dict1 = {'a': 1, 'b': 2}, dict2 = {'c': 3, 'd': 4}`
- `Sample Output: {'a': 1, 'b': 2, 'c': 3, 'd': 4}`
"""

# Please write The solution Here for above question 8:
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
res={}
for i in dict1:
  res[i]=dict1[i]
for i in dict2:
  res[i]=dict2[i]
print(res)

"""### Question 9 : Write a function that sorts a dictionary by its values in ascending order.
- `Sample Input: my_dict = {'a': 5, 'b': 2, 'c': 7}`
- `Sample Output: {'b': 2, 'a': 5, 'c': 7}`
"""

# Please write The solution Here for above question 9:
my_dict = {'a': 5, 'b': 2, 'c': 7}

"""### Question 10 : Write a function that returns the key in a dictionary with the maximum value.
- `Sample Input: my_dict = {'a': 5, 'b': 2, 'c': 7}`
- `Sample Output: 'c'`
"""

# Please write The solution Here for above question 10:
my_dict = {'a': 5, 'b': 2, 'c': 7}
res=max(my_dict.keys())
print(res)

