# -*- coding: utf-8 -*-
"""Copy of Python Strings .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q3XlckPdXg6bQWlawAgQCwdT1TIa10Ao

<a href="https://www.viharatech.com"><img src="https://miro.medium.com/v2/resize:fit:828/format:webp/1*on2Bpj6A5gfd-CzaFOAZRA.jpeg"></a>


- `Welcome to our interactive learning session! In this Jupyter notebook, you'll find a series of questions related to Python String Concept. To maximize your learning, please write Python code in the cell below each question and execute it. This hands-on practice will help reinforce your understanding of the concepts. Feel free to reach out if you have any questions or need assistance. Happy coding! 💻🐍 `

### Question 1: Write a Python program to count the number of characters in a string without using len function.

- `sample input : `
    - `var = 'python java'`
- `sample output :`
    - `result : 11`
"""

# Please write The solution Here for above question 1:
var=input("Enter a String: ")
c=0
for i in var:
  c+=1
print(c)

"""### Question 2: Write a Python program to reverse a string without using [::-1]

- `sample input : `
    - `var = 'python'`
- `sample output :`
    - `result : nohtyp`
"""

# Please write The solution Here for above question 2:
var=input("Enter a string: ")
rev=" "
for ch in var:
  rev=ch+rev
print(rev)

"""### Question 3: Write a Python program to check if a string is a palindrome don't use [::-1].

- `sample input : `
    - `var = 'NUN'`
- `sample output :`
    - `result : It is a Palindrome`
    
- `palindrome concept = https://www.dictionary.com/e/palindromic-word/#:~:text=A%20palindrome%20is%20a%20word,roots%20in%20the%20early%201600s.`
"""

# Please write The solution Here for above question 3:
var=input("Enter a string: ")
rev=""
for i in var:
  rev=i+rev
if rev==var:
  print("It is a palindrom")
else:
  print("It is not a palindrom")

"""### Question 4: Write a Python program to find the most common character in a string.

- `sample input : `
    - `var = 'Hello world '`
- `sample output :`
    - `result : l, because l is repeating 3 times `
"""

# Please write The solution Here for above question 4:
a="Hello world"
b={}
for i in a:
  if i in b:
    b[i]=b[i]+1
  else:
    b[i]=1

max_count=0
max_char=""

for i in b:
  if b[i] > max_count:
    max_count=b[i]
    max_char=i
print("result : ", max_char ,"because", max_char ," is repeating" ,max_count ,"times" )

"""### Question 5: Write a Python program to check if two strings are anagrams.

- `sample input : `
    - `var1 = 'listen'`
    - `var2 = 'silent'`
- `sample output :`
    - `result : both are anagram because characters in var2 should present in var1 `
"""

# Please write The solution Here for above question 5:
var1=input("Enter a string: ")
var2=input("Enter a string: ")
len1=0
len2=0
for ch in var1:
  len1+=1 #6
for ch in var2:
  len2+=1 #6
if len1!=len2:
  print("Result : Both are not anagrams")
else:
  count=0
  for ch1 in var1:
    for ch2 in var2: #first iterate the single char to found in first iteration if found it will not search stop the iteration so will change in first iteration to next char
      if ch1==ch2:
        count+=1  #6
        break
  if count==len1: #6==6
    print("result : both are anagram because characters in var2 should present in var1")
  else:
    print("result : both are not anagram because characters in var2 should not present in var1")

"""### Question 6: Write a Python program to remove all the vowels from a string.

- `sample input : `
    - `var = 'python'`
- `sample output :`
    - `result : pythn , because vowels are [AEIOUaeiou]`
"""

# Please write The solution Here for above question 6:
var="python"
res=""
for i in var:
  if i!='a'and i!='e'and i!='i'and i!='o'and i!='u':
    res+=i
print("result:",res,"because vowels are [AEIOUaeiou]")

"""### Question 7: Write a Python program to find the longest word in a string.

- `sample input : `
    - `var = 'python is Easy Language'`
- `sample output :`
    - `result : Language`
"""

# Please write The solution Here for above question 7:
var="python is Easy Language"
word=""
longest=""
for ch in var:
  if ch != " ":
    word+=ch
  else:
    if len(word)>len(longest):
      longest=word
    word= ""
if len(word)>len(longest):
      longest=word

print("Result:",longest)

"""### Question 8: Write a Python program to capitalize the first letter of each word in a string [dont use built-in-function called title].

- `sample input : `
    - `var = 'python is easy'`
- `sample output :`
    - `result : Python Is Easy`
"""

# Please write The solution Here for above question 8:
var = "python is easy"
result = ""

for i in range(len(var)):
    if i == 0 or var[i - 1] == " ":
        result += chr(ord(var[i]) - 32)
    else:
        result += var[i]

print("Result :", result)

"""### Question 9: Write a Python program to find the frequency of each character in a string.

- `sample input : `
    - `var = 'sharuk khan'`
- `sample output :`
    - `result : {'s': 1, 'h': 2, 'a': 2, 'r': 1, 'u': 1, 'k': 2, ' ': 1, 'n': 1}`
"""

# Please write The solution Here for above question 9:
a=input("Enter a String: ")
result={ }
for i in a:
  if i in result:
    result[i]=result[i]+1
  else:
    result[i]=1
print("result: ",result)

"""### Question 10: write a python programme to find the sum of all the even characters based on Ascii values

- `sample input : `
    - `var = 'sharuk khan'`
- `sample output :`
    - `result : 464`

"""

# Please write The solution Here for above question 10:
var=input("Enter a string: ")
sum=0
for i in var:
  Ascii_value=ord(i)
  if Ascii_value%2==0:
    sum+=Ascii_value
print("result: ",sum)