# -*- coding: utf-8 -*-
"""Copy of Python List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCLnAuuDn5qF0pfWgAJ9cS3XnNTadg-G

<a href="https://www.viharatech.com"><img src="https://miro.medium.com/v2/resize:fit:828/format:webp/1*on2Bpj6A5gfd-CzaFOAZRA.jpeg"></a>


- `Welcome to our interactive learning session! In this Jupyter notebook, you'll find a series of questions related to Python List Concept. To maximize your learning, please write Python code in the cell below each question and execute it. This hands-on practice will help reinforce your understanding of the concepts. Feel free to reach out if you have any questions or need assistance. Happy coding! 💻🐍 `

### Question 1: Write a Python program to count the number of elements in a list without using len.


- `sample input : `
    - `var = [10,11,12,13]`
- `sample output :`
    - `result : 4`
"""

# Please write The solution Here for above question 1:
var=[10,23,44,5,8,7,8,8,5,7,44]
sum=0
for i in var:
  sum+=1
print(sum)

"""### Question 2: Write a Python program to find the maximum and minimum values in a given list.

- `sample input : `
    - `var = [10,11,12,13,14,15]`
- `sample output :`
    - `result : max = 15 , min = 10`
"""

# Please write The solution Here for above question 2:
var=[10,11,12,13,14,15]
max=var[0]
min=var[0]
for i in var:
  if i>max:
    max=i
  if i<min:
    min=i
print(max)
print(min)

"""### Question 3: Write a Python program to remove the first occurrence of a specified element from a list.

- `sample input : `
    - `var = [1,2,3,4,2,5]`
- `sample output :`
    - `result : [1,3,4,2,5]`
    
"""

# Please write The solution Here for above question 3:
var= [1,2,3,4,2,5]
res=[]
remove=False
for i in var:
  if i==2 and remove==False:
    remove=True
  else:
    res.append(i)

print("Result: ",res)

"""
### Question 4: Write a Python program to find the average of all the elements in a list.


- `sample input : `
    - `var = [1,2,3,4,2,5]`
- `sample output :`
    - `result : 2.833 `"""

# Please write The solution Here for above question 4:
var = [1,2,3,4,2,5]
total=0
count=0
for i in var:
  total+=i
  count+=1
avg=total/count
print(avg)

"""### Question 5: Write a Python program to check if a list is empty or not.


- `sample input : `
    - `var1 = [1,2]`
- `sample output :`
    - `result : Not empty`
    
- `sample input : `
    - `var1 = []`
- `sample output :`
    - `result :empty`
    

"""

# Please write The solution Here for above question 5:
var1 = [1,2,3,4]
if var1==[]:
  print("empty")
else:
  print("Not empty")

"""### Question 6:  Write a Python program to find the index of a specified element in a list..

- `sample input : `
    - `var = [1,2,3,4,2,5]`
- `sample output :`
    - `result : 3 index is 2`
"""

# Please write The solution Here for above question 6:
var = [1, 2, 3, 4, 2, 5]
find=2
for i in range(len(var)):
  if var[i]==find:
    print("Result: ",find," index is",i)
    break

"""### Question 7: Write a Python program to find which number is palindrome in below given list .

- `sample input : `
    - `var = [134,121,155]`
- `sample output :`
    - `result : 134 is not a palindome , 121 is a palindrome `
"""

# Please write The solution Here for above question 7:
var = [134,121,155]
for i in var:
  temp=i
  rev=0

  while temp>0:
    d=temp%10
    rev=rev*10+d
    temp=temp//10

  if i==rev:
    print(i,"is a palindrome")
  else:
    print(i,"is not a palindrome")

"""### Question 8: Write a Python program to find the common elements between two lists.

- `sample input : `
    - `var1 = [1,2,3,4,10]`
    - `var2 = [10,11,12,14]`
- `sample output :`
    - `result : 10`
"""

# Please write The solution Here for above question 8:
var1 = [1,2,3,4,10]
var2 = [10,11,12,14]
for i in var1:
  for j in var2:
    if i==j:
      print(i)

"""### Question 9: Write a Python program to remove the duplicates from a list

- `sample input : `
    - `var = [10,11,12,10,12,24]`
- `sample output :`
    - `result : [10,11,12,24]`
"""

# Please write The solution Here for above question 9:
var = [10,11,12,10,12,24]
res=[]
for i in var:
  if i not in res:
    res.append(i)
print(res)

"""### Question 10:  Write a Python program to sort a list of strings in Ascii Order [Ascending order]


- `sample input : `
    - `var = ['a' , 'c' , 'b']`
- `sample output :`
    - `result : ['a' , 'b' , 'c']`

"""

# Please write The solution Here for above question 10:
var = ['a' , 'c' , 'b']
for i in range(len(var)):
  for j in range(i+1,len(var)):
    if ord(var[i]) > ord(var[j]):
      temp=var[i]
      var[i]=var[j]
      var[j]=temp
print("Result: ",var)